### ISSUE TITLE
Style landline layers

### ISSUE THREAD

**Issue by arouault** [MAPC/trailmap2#17]
Distinguish the Landline layers into 2 greenways and walking trails. Style proposed/in progress as dashed; and existing as a solid line.

**Comment by allthesignals** [comment]
@arouault 
Not sure what colors to use for this - I can't pull from the old trailmap.mapc.org because it doesn't seem like these categories exist. Are Greenways grouped together?

Here are the categories:
 - Greenway route and Regional Walking trail
 - Greenway Route
 - Regional Walking Trail

Separately, this doesn't sound like it's only styling - does this need to be filterable? I think we originally said it'd be its own clickable layer, but we could have the styling be different. Just need a way to symbolize it.
